### PR TITLE
Update the wheel builds for newer python versions and drop support for py 36 and 37

### LINKED ISSUE #43: broken installation with astropy v5
I am trying to install it, but there seems to be an important issue with the newer `astropy`. 

I cloned the `casa-formats-io` repo, and tried to install it with both `pip` and `python setup.py` and got a similar error message.  See below.

```
python setup.py develop did not run successfully.
â exit code: 1
â°â> [36 lines of output]
    running develop
    /private/var/folders/2n/6gk_yf0d1zvdwj6wy12h_klr0000gn/T/pip-build-env-pidylk7f/overlay/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /private/var/folders/2n/6gk_yf0d1zvdwj6wy12h_klr0000gn/T/pip-build-env-pidylk7f/overlay/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running egg_info
    writing casa_formats_io.egg-info/PKG-INFO
    writing dependency_links to casa_formats_io.egg-info/dependency_links.txt
    writing entry points to casa_formats_io.egg-info/entry_points.txt
    writing requirements to casa_formats_io.egg-info/requires.txt
    writing top-level names to casa_formats_io.egg-info/top_level.txt
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'README.md'
    warning: no files found matching 'LICENSE.rst'
    warning: no files found matching '*.c' under directory '*.pyx'
    warning: no files found matching '*.pxd' under directory '*.pyx'
    warning: no files found matching '*' under directory 'licenses'
    warning: no files found matching '*' under directory 'cextern'
    warning: no files found matching '*' under directory 'scripts'
    no previously-included directories found matching 'build'
    no previously-included directories found matching 'docs/_build'
    no previously-included directories found matching 'docs/api'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.o' found anywhere in distribution
    adding license file 'LICENSE'
    writing manifest file 'casa_formats_io.egg-info/SOURCES.txt'
    running build_ext
    building 'casa_formats_io._casa_chunking' extension
    x86_64-apple-darwin13.4.0-clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/jpineda/miniconda3/envs/py3/include -fPIC -O2 -isystem /Users/jpineda/miniconda3/envs/py3/include -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/jpineda/miniconda3/envs/py3/include -D_FORTIFY_SOURCE=2 -isystem /Users/jpineda/miniconda3/envs/py3/include -I/private/var/folders/2n/6gk_yf0d1zvdwj6wy12h_klr0000gn/T/pip-build-env-pidylk7f/overlay/lib/python3.9/site-packages/numpy/core/include -I/Users/jpineda/miniconda3/envs/py3/include/python3.9 -c casa_formats_io/_casa_chunking.c -o build/temp.macosx-10.9-x86_64-cpython-39/casa_formats_io/_casa_chunking.o
    In file included from casa_formats_io/_casa_chunking.c:3:
    In file included from /Users/jpineda/miniconda3/envs/py3/include/python3.9/Python.h:91:
    /Users/jpineda/miniconda3/envs/py3/include/python3.9/bytearrayobject.h:9:10: fatal error: 'stdarg.h' file not found
    #include <stdarg.h>
             ^~~~~~~~~~
    1 error generated.
    error: command '/Users/jpineda/miniconda3/envs/py3/bin/x86_64-apple-darwin13.4.0-clang' failed with exit code 1
    [end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
```

I am using python 3.9.10 and astropy 5.0.2. This is the version of GCC installed
```
(py3) bash-3.2$ gcc -v
Apple clang version 13.1.6 (clang-1316.0.21.2.3)
```
and the main python environment is managed with `conda`. What else would you like me to check? Because this is breaking both `SpectralCube` and `Turbustat` for me. :-( 

@keflavich @e-koch

### PR DESCRIPTION
**Pull request by e-koch**
This should fix #43 for pip installs.

### CODE REVIEW

**Review by keflavich — APPROVED** [review]

**Comment by e-koch** [comment]
One of the py37 versions is now failing to build...

**Comment by e-koch** [comment]
@keflavich @astrofrog  Two things here:

1. The failures are a version issue with `markupsafe` when building astropy v4.3.1 (https://github.com/astropy/astropy/pull/12877). But it's not using the wheels for numpy or astropy for whatever reason (https://github.com/radio-astro-tools/casa-formats-io/runs/6325393121?check_suite_focus=true#step:5:2426).
2. It's taking ~1 hr to build/test the wheels for 5 python versions (3.6 - 3.10). Given CASA >6.4 is using at least python 3.8, can we start dropping support for 3.6 and 3.7?

**Comment by keflavich** [comment]
yes, :+1: to dropping older py's

**Comment by astrofrog** [comment]
Agree also with dropping older Pythons

**Comment by e-koch** [comment]
The wheels build is still very slow (~90 min) but passes. A quick check on the version updates would be appreciated!

**Review by keflavich — APPROVED** [review]

**Comment by keflavich** [comment]
I can't see any problems.  I'm amused that `'3.10'` requires quotes.

**Pull request merged**
