### PR TITLE
Update CI configuration and fix deprecations

### PR DESCRIPTION
**Pull request by astrofrog**
WIP as I need to fix some deprecations and there are now some test errors

### CODE REVIEW

**Comment by astrofrog** [comment]
The conda jobs are failing but I think it's due to tox-conda not properly supporting tox 4, so I think we can ignore for now.

**Review by keflavich — APPROVED** [review]

**Comment by keflavich** [comment]
This is obviously a big improvement.  Any idea what the remaining few failures are?

**Comment by astrofrog** [comment]
@keflavich - let's just disable the tests for now, I'll open an issue to remind us.

**Review by e-koch — APPROVED** [review]

**Comment by astrofrog** [comment]
I'm skipping the building of the Python 3.12 wheels for now since there is a setuptools issue. It doesn't matter anyway since we don't actually build 3.12 wheels, we just test on 3.12 (but we have universal wheels that use the limited API)

**Pull request merged**
